resolver: lts-24.29 # GHC 9.10.3
packages:
  - extract-cons
  - template-haskell-lenses
  - template-haskell-natural
  - examples/packed
  - examples/pushable

extra-deps:
  - packed-data-0.1.0.3
  - linear-base-0.4.0
