name: extract-cons
version: 1.0.0.0
copyright: "MIT"

default-extensions:
  - TemplateHaskell
  - RecordWildCards
  - MultiParamTypeClasses
  - LambdaCase

dependencies:
  - base
  - template-haskell
  - syb

library:
  source-dirs: src
