name: lens-adt
version: 1.0.0.0

description: "Generate lenses for non-record ADTs with one constructor"

default-extensions:
  - TemplateHaskell
  - RecordWildCards
  - MultiParamTypeClasses
  - LambdaCase

dependencies:
  - base
  - template-haskell
  - lens
  - generic-lens

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
